// Mock data for development and testing - showing all possible statuses

export const mockOrders = [
  {
    id: '1',
    order_number: 'ORD-2025-001',
    customer_name: 'Ahmed Khan',
    customer_phone: '+92-300-1234567',
    customer_email: 'ahmed@example.com',
    customer_address: '123 Main Street, Gulberg',
    city: 'Lahore',
    total_amount: 5500,
    status: 'pending',
    verification_status: 'pending',
    confirmation_status: 'pending',
    created_at: new Date().toISOString(),
    items: [{ name: 'Product A', quantity: 2, price: 2750 }],
  },
  {
    id: '2',
    order_number: 'ORD-2025-002',
    customer_name: 'Fatima Ali',
    customer_phone: '+92-321-9876543',
    customer_email: 'fatima@example.com',
    customer_address: '456 Garden Road, DHA',
    city: 'Karachi',
    total_amount: 8900,
    status: 'pending',
    verification_status: 'pending_address',
    confirmation_status: 'pending',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    items: [{ name: 'Product B', quantity: 3, price: 2967 }],
  },
  {
    id: '3',
    order_number: 'ORD-2025-003',
    customer_name: 'Hassan Raza',
    customer_phone: '+92-333-5555555',
    customer_email: 'hassan@example.com',
    customer_address: '789 Park Avenue, F-8',
    city: 'Islamabad',
    total_amount: 12000,
    status: 'booked',
    verification_status: 'verified',
    confirmation_status: 'confirmed',
    created_at: new Date(Date.now() - 172800000).toISOString(),
    items: [{ name: 'Product C', quantity: 4, price: 3000 }],
  },
  {
    id: '4',
    order_number: 'ORD-2025-004',
    customer_name: 'Zainab Ahmed',
    customer_phone: '+92-345-7777777',
    customer_email: 'zainab@example.com',
    customer_address: '321 Mall Road, Cantt',
    city: 'Rawalpindi',
    total_amount: 6500,
    status: 'dispatched',
    verification_status: 'verified',
    confirmation_status: 'confirmed',
    dispatched_at: new Date(Date.now() - 259200000).toISOString(),
    created_at: new Date(Date.now() - 345600000).toISOString(),
    items: [{ name: 'Product D', quantity: 1, price: 6500 }],
  },
  {
    id: '5',
    order_number: 'ORD-2025-005',
    customer_name: 'Bilal Shah',
    customer_phone: '+92-300-9999999',
    customer_email: 'bilal@example.com',
    customer_address: '555 University Road, Johar Town',
    city: 'Lahore',
    total_amount: 4200,
    status: 'delivered',
    verification_status: 'verified',
    confirmation_status: 'confirmed',
    delivered_at: new Date(Date.now() - 432000000).toISOString(),
    created_at: new Date(Date.now() - 604800000).toISOString(),
    items: [{ name: 'Product E', quantity: 2, price: 2100 }],
  },
  {
    id: '6',
    order_number: 'ORD-2025-006',
    customer_name: 'Sara Malik',
    customer_phone: '+92-312-1111111',
    customer_email: 'sara@example.com',
    customer_address: '999 Blue Area, Sector G-7',
    city: 'Islamabad',
    total_amount: 3500,
    status: 'cancelled',
    verification_status: 'rejected',
    confirmation_status: 'cancelled',
    created_at: new Date(Date.now() - 518400000).toISOString(),
    items: [{ name: 'Product F', quantity: 1, price: 3500 }],
  },
  {
    id: '7',
    order_number: 'ORD-2025-007',
    customer_name: 'Usman Tariq',
    customer_phone: '+92-333-2222222',
    customer_email: 'usman@example.com',
    customer_address: '777 Jail Road, Model Town',
    city: 'Lahore',
    total_amount: 7800,
    status: 'returned',
    verification_status: 'verified',
    confirmation_status: 'confirmed',
    created_at: new Date(Date.now() - 691200000).toISOString(),
    items: [{ name: 'Product G', quantity: 3, price: 2600 }],
  },
  {
    id: '8',
    order_number: 'ORD-2025-008',
    customer_name: 'Ayesha Noor',
    customer_phone: '+92-321-3333333',
    customer_email: 'ayesha@example.com',
    customer_address: '111 Shahrah-e-Faisal, Clifton',
    city: 'Karachi',
    total_amount: 9600,
    status: 'pending',
    verification_status: 'pending_confirmation',
    confirmation_status: 'pending',
    created_at: new Date(Date.now() - 43200000).toISOString(),
    items: [{ name: 'Product H', quantity: 2, price: 4800 }],
  },
];

export const mockDispatches = [
  {
    id: 'd1',
    order_id: '4',
    tracking_id: 'TRK-LPD-2025-001',
    courier: 'Leopard',
    status: 'pending',
    dispatch_date: new Date().toISOString(),
    created_at: new Date().toISOString(),
    orders: {
      order_number: 'ORD-2025-101',
      customer_name: 'Ali Hassan',
      customer_phone: '+92-300-4444444',
      customer_address: '123 Model Colony, Karachi',
      city: 'Karachi',
      total_amount: 4500,
    }
  },
  {
    id: 'd2',
    order_id: '5',
    tracking_id: 'TRK-TCS-2025-002',
    courier: 'TCS',
    status: 'in_transit',
    dispatch_date: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    orders: {
      order_number: 'ORD-2025-102',
      customer_name: 'Sana Ahmed',
      customer_phone: '+92-321-5555555',
      customer_address: '456 Cavalry Ground, Lahore',
      city: 'Lahore',
      total_amount: 6700,
    }
  },
  {
    id: 'd3',
    order_id: '6',
    tracking_id: 'TRK-PTX-2025-003',
    courier: 'Postex',
    status: 'completed',
    dispatch_date: new Date(Date.now() - 259200000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
    orders: {
      order_number: 'ORD-2025-103',
      customer_name: 'Hamza Malik',
      customer_phone: '+92-333-6666666',
      customer_address: '789 F-10, Islamabad',
      city: 'Islamabad',
      total_amount: 8200,
    }
  },
  {
    id: 'd4',
    order_id: '7',
    tracking_id: 'TRK-LPD-2025-004',
    courier: 'Leopard',
    status: 'delivered',
    dispatch_date: new Date(Date.now() - 432000000).toISOString(),
    created_at: new Date(Date.now() - 432000000).toISOString(),
    orders: {
      order_number: 'ORD-2025-104',
      customer_name: 'Zara Khan',
      customer_phone: '+92-345-7777777',
      customer_address: '321 DHA Phase 5, Karachi',
      city: 'Karachi',
      total_amount: 5900,
    }
  },
];

export const mockReturns = [
  {
    id: 'r1',
    order_id: '7',
    tracking_id: 'RTN-2025-001',
    reason: 'Wrong size',
    worth: 7800,
    return_status: 'in_transit',
    date: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    orders: {
      order_number: 'ORD-2025-007',
      customer_name: 'Usman Tariq',
      customer_phone: '+92-333-2222222',
      customer_email: 'usman@example.com',
    }
  },
  {
    id: 'r2',
    order_id: '8',
    tracking_id: 'RTN-2025-002',
    reason: 'Defective product',
    worth: 4200,
    return_status: 'received',
    date: new Date(Date.now() - 172800000).toISOString(),
    received_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    orders: {
      order_number: 'ORD-2025-201',
      customer_name: 'Nadia Rehman',
      customer_phone: '+92-300-8888888',
      customer_email: 'nadia@example.com',
    }
  },
  {
    id: 'r3',
    order_id: '9',
    tracking_id: 'RTN-2025-003',
    reason: 'Changed mind',
    worth: 6500,
    return_status: 'processed',
    date: new Date(Date.now() - 259200000).toISOString(),
    received_at: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
    orders: {
      order_number: 'ORD-2025-202',
      customer_name: 'Imran Sheikh',
      customer_phone: '+92-321-9999999',
      customer_email: 'imran@example.com',
    }
  },
  {
    id: 'r4',
    order_id: '10',
    tracking_id: 'RTN-2025-004',
    reason: 'Wrong color',
    worth: 3200,
    return_status: 'completed',
    date: new Date(Date.now() - 432000000).toISOString(),
    received_at: new Date(Date.now() - 259200000).toISOString(),
    created_at: new Date(Date.now() - 432000000).toISOString(),
    orders: {
      order_number: 'ORD-2025-203',
      customer_name: 'Mariam Aziz',
      customer_phone: '+92-333-1010101',
      customer_email: 'mariam@example.com',
    }
  },
];

export const mockPurchaseOrders = [
  {
    id: 'po1',
    po_number: 'PO-2025-0001',
    status: 'draft',
    order_date: new Date().toISOString(),
    expected_delivery_date: new Date(Date.now() + 604800000).toISOString(),
    total_amount: 125000,
    suppliers: { name: 'Alpha Suppliers' },
    outlets: { name: 'Main Warehouse' },
  },
  {
    id: 'po2',
    po_number: 'PO-2025-0002',
    status: 'sent',
    order_date: new Date(Date.now() - 86400000).toISOString(),
    expected_delivery_date: new Date(Date.now() + 518400000).toISOString(),
    total_amount: 78000,
    suppliers: { name: 'Beta Trading' },
    outlets: { name: 'Main Warehouse' },
  },
  {
    id: 'po3',
    po_number: 'PO-2025-0003',
    status: 'confirmed',
    order_date: new Date(Date.now() - 172800000).toISOString(),
    expected_delivery_date: new Date(Date.now() + 432000000).toISOString(),
    total_amount: 156000,
    suppliers: { name: 'Gamma Imports' },
    outlets: { name: 'Main Warehouse' },
  },
  {
    id: 'po4',
    po_number: 'PO-2025-0004',
    status: 'partially_received',
    order_date: new Date(Date.now() - 345600000).toISOString(),
    expected_delivery_date: new Date(Date.now() + 172800000).toISOString(),
    total_amount: 92000,
    suppliers: { name: 'Delta Wholesale' },
    outlets: { name: 'Main Warehouse' },
  },
  {
    id: 'po5',
    po_number: 'PO-2025-0005',
    status: 'completed',
    order_date: new Date(Date.now() - 604800000).toISOString(),
    expected_delivery_date: new Date(Date.now() - 86400000).toISOString(),
    total_amount: 210000,
    suppliers: { name: 'Epsilon Distributors' },
    outlets: { name: 'Main Warehouse' },
  },
  {
    id: 'po6',
    po_number: 'PO-2025-0006',
    status: 'cancelled',
    order_date: new Date(Date.now() - 432000000).toISOString(),
    expected_delivery_date: new Date(Date.now() + 259200000).toISOString(),
    total_amount: 45000,
    suppliers: { name: 'Zeta Supplies' },
    outlets: { name: 'Main Warehouse' },
  },
];

export const mockInventory = [
  {
    id: 'inv1',
    product_id: 'p1',
    outlet_id: 'o1',
    quantity: 150,
    reserved_quantity: 20,
    available_quantity: 130,
    product: {
      sku: 'SKU-001',
      name: 'Product Alpha',
      category: 'Electronics',
      reorder_level: 50,
      price: 2500,
    },
    outlet: { name: 'Main Warehouse' },
  },
  {
    id: 'inv2',
    product_id: 'p2',
    outlet_id: 'o1',
    quantity: 35,
    reserved_quantity: 5,
    available_quantity: 30,
    product: {
      sku: 'SKU-002',
      name: 'Product Beta',
      category: 'Clothing',
      reorder_level: 40,
      price: 1800,
    },
    outlet: { name: 'Main Warehouse' },
  },
  {
    id: 'inv3',
    product_id: 'p3',
    outlet_id: 'o2',
    quantity: 0,
    reserved_quantity: 0,
    available_quantity: 0,
    product: {
      sku: 'SKU-003',
      name: 'Product Gamma',
      category: 'Home & Garden',
      reorder_level: 25,
      price: 3200,
    },
    outlet: { name: 'Outlet A' },
  },
  {
    id: 'inv4',
    product_id: 'p4',
    outlet_id: 'o1',
    quantity: 8,
    reserved_quantity: 2,
    available_quantity: 6,
    product: {
      sku: 'SKU-004',
      name: 'Product Delta',
      category: 'Sports',
      reorder_level: 15,
      price: 4500,
    },
    outlet: { name: 'Main Warehouse' },
  },
  {
    id: 'inv5',
    product_id: 'p5',
    outlet_id: 'o3',
    quantity: 250,
    reserved_quantity: 50,
    available_quantity: 200,
    product: {
      sku: 'SKU-005',
      name: 'Product Epsilon',
      category: 'Beauty',
      reorder_level: 100,
      price: 1200,
    },
    outlet: { name: 'Outlet B' },
  },
];
