-- Corrected all phases with proper product_type and unit_type values
CREATE OR REPLACE FUNCTION public.log_role_changes()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
BEGIN IF auth.uid() IS NULL THEN RETURN NEW; END IF; IF TG_OP = 'UPDATE' AND OLD.role IS DISTINCT FROM NEW.role THEN INSERT INTO public.activity_logs (user_id, action, entity_type, entity_id, details) VALUES (auth.uid(), 'role_change', 'profiles', NEW.id, jsonb_build_object('old_role', OLD.role, 'new_role', NEW.role, 'target_user_id', NEW.id, 'target_user_email', NEW.email)); END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.log_user_roles_changes()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE target_email text; BEGIN IF auth.uid() IS NULL THEN IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF; END IF; IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN SELECT email INTO target_email FROM public.profiles WHERE id = NEW.user_id; END IF; IF TG_OP = 'INSERT' THEN INSERT INTO public.activity_logs (user_id, action, entity_type, entity_id, details) VALUES (auth.uid(), 'role_assigned', 'user_roles', NEW.id, jsonb_build_object('role', NEW.role, 'target_user_id', NEW.user_id, 'target_user_email', target_email, 'is_active', NEW.is_active)); ELSIF TG_OP = 'UPDATE' THEN INSERT INTO public.activity_logs (user_id, action, entity_type, entity_id, details) VALUES (auth.uid(), 'role_updated', 'user_roles', NEW.id, jsonb_build_object('old_is_active', OLD.is_active, 'new_is_active', NEW.is_active, 'role', NEW.role, 'target_user_id', NEW.user_id, 'target_user_email', target_email)); ELSIF TG_OP = 'DELETE' THEN SELECT email INTO target_email FROM public.profiles WHERE id = OLD.user_id; INSERT INTO public.activity_logs (user_id, action, entity_type, entity_id, details) VALUES (auth.uid(), 'role_removed', 'user_roles', OLD.id, jsonb_build_object('role', OLD.role, 'target_user_id', OLD.user_id, 'target_user_email', target_email)); RETURN OLD; END IF; RETURN NEW; END; $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = 'c3ad9cce-9429-4710-ade5-06dbd8512f02' AND role = 'super_manager') THEN INSERT INTO public.user_roles (user_id, role, assigned_by, is_active) VALUES ('c3ad9cce-9429-4710-ade5-06dbd8512f02', 'super_manager', 'ff812d62-9e9e-4ba6-a462-45ecb6fb4b16', true); ELSE UPDATE public.user_roles SET is_active = true, updated_at = now() WHERE user_id = 'c3ad9cce-9429-4710-ade5-06dbd8512f02' AND role = 'super_manager'; END IF; UPDATE public.profiles SET role = 'super_manager' WHERE id = 'c3ad9cce-9429-4710-ade5-06dbd8512f02'; END $$;

DROP POLICY IF EXISTS "Managers can assign staff roles" ON public.user_roles;
DROP POLICY IF EXISTS "Managers can update staff roles" ON public.user_roles;
DROP POLICY IF EXISTS "Managers can delete staff roles" ON public.user_roles;

CREATE POLICY "Super managers can assign most roles" ON public.user_roles FOR INSERT TO authenticated WITH CHECK ((EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_manager' AND ur.is_active = true) AND role IN ('staff','dispatch_manager','returns_manager','warehouse_manager','store_manager','supplier') AND user_id <> auth.uid()) OR EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_admin' AND ur.is_active = true));
CREATE POLICY "Super managers can update most roles" ON public.user_roles FOR UPDATE TO authenticated USING ((EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_manager' AND ur.is_active = true) AND role IN ('staff','dispatch_manager','returns_manager','warehouse_manager','store_manager','supplier')) OR EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_admin' AND ur.is_active = true)) WITH CHECK ((EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_manager' AND ur.is_active = true) AND role IN ('staff','dispatch_manager','returns_manager','warehouse_manager','store_manager','supplier') AND user_id <> auth.uid()) OR EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_admin' AND ur.is_active = true));
CREATE POLICY "Super managers can delete most roles" ON public.user_roles FOR DELETE TO authenticated USING ((EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_manager' AND ur.is_active = true) AND role IN ('staff','dispatch_manager','returns_manager','warehouse_manager','store_manager','supplier')) OR EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = auth.uid() AND ur.role = 'super_admin' AND ur.is_active = true));

DO $$
DECLARE v_wh uuid; v_prod uuid; v_id uuid; v_sup uuid; v_po uuid; BEGIN
  IF NOT EXISTS (SELECT 1 FROM suppliers WHERE code = 'SUP-ABC-001') THEN INSERT INTO suppliers (code, name, contact_person, email, phone, address, payment_terms, status) VALUES ('SUP-ABC-001','ABC Textiles Ltd','Ahmed Khan','ahmed@abctextiles.com','03001234567','Plot 123, Industrial Area, Karachi','Net 30','active'); END IF;
  IF NOT EXISTS (SELECT 1 FROM suppliers WHERE code = 'SUP-XYZ-001') THEN INSERT INTO suppliers (code, name, contact_person, email, phone, address, payment_terms, status) VALUES ('SUP-XYZ-001','XYZ Electronics','Sara Ahmed','sara@xyzelectronics.com','03009876543','Building 5, Tech Park, Lahore','Net 45','active'); END IF;
  IF NOT EXISTS (SELECT 1 FROM suppliers WHERE code = 'SUP-PPP-001') THEN INSERT INTO suppliers (code, name, contact_person, email, phone, address, payment_terms, status) VALUES ('SUP-PPP-001','Premium Packaging Co','Ali Raza','ali@premiumpkg.com','03005555555','Warehouse Complex, Faisalabad','Net 15','active'); END IF;

  SELECT id INTO v_wh FROM outlets WHERE name = 'Main Warehouse' LIMIT 1;
  SELECT id INTO v_prod FROM products WHERE name = 'Premium Cotton T-Shirt' LIMIT 1;
  IF v_prod IS NOT NULL AND v_wh IS NOT NULL THEN UPDATE inventory SET quantity = 500, reserved_quantity = COALESCE(reserved_quantity,0), updated_at = now() WHERE product_id = v_prod AND outlet_id = v_wh; IF NOT FOUND THEN INSERT INTO inventory (product_id, outlet_id, quantity, reserved_quantity) VALUES (v_prod, v_wh, 500, 0); END IF; END IF;

  IF NOT EXISTS (SELECT 1 FROM products WHERE sku = 'DJ-BLUE-001') THEN INSERT INTO products (name, sku, barcode, category, description, cost, price, reorder_level, is_active, product_type, unit_type) VALUES ('Denim Jeans - Blue','DJ-BLUE-001','1234567890124','Apparel','Classic blue denim jeans',1200,2500,10,true,'finished','pieces'); END IF;
  IF NOT EXISTS (SELECT 1 FROM products WHERE sku = 'LW-BRN-001') THEN INSERT INTO products (name, sku, barcode, category, description, cost, price, reorder_level, is_active, product_type, unit_type) VALUES ('Leather Wallet - Brown','LW-BRN-001','1234567890125','Accessories','Genuine leather wallet',450,1200,20,true,'finished','pieces'); END IF;
  IF NOT EXISTS (SELECT 1 FROM products WHERE sku = 'SN-WHT-001') THEN INSERT INTO products (name, sku, barcode, category, description, cost, price, reorder_level, is_active, product_type, unit_type) VALUES ('Sneakers - White','SN-WHT-001','1234567890126','Footwear','Comfortable white sneakers',1800,3500,15,true,'finished','pieces'); END IF;

  IF v_wh IS NOT NULL THEN FOR v_id IN SELECT id FROM products WHERE sku IN ('DJ-BLUE-001','LW-BRN-001','SN-WHT-001') LOOP UPDATE inventory SET quantity = 200, reserved_quantity = COALESCE(reserved_quantity,0), updated_at = now() WHERE product_id = v_id AND outlet_id = v_wh; IF NOT FOUND THEN INSERT INTO inventory (product_id, outlet_id, quantity, reserved_quantity) VALUES (v_id, v_wh, 200, 0); END IF; END LOOP; END IF;

  SELECT id INTO v_sup FROM suppliers WHERE code = 'SUP-ABC-001' LIMIT 1;
  SELECT id INTO v_prod FROM products WHERE name = 'Premium Cotton T-Shirt' LIMIT 1;
  IF v_sup IS NOT NULL AND v_prod IS NOT NULL THEN INSERT INTO purchase_orders (po_number, supplier_id, status, total_amount, expected_delivery_date, notes) VALUES ('PO-TEST-' || TO_CHAR(NOW(),'YYYYMMDDHH24MISS'), v_sup, 'pending', 50000, NOW() + INTERVAL '7 days', 'Test PO for restocking') RETURNING id INTO v_po; IF v_po IS NOT NULL THEN INSERT INTO purchase_order_items (purchase_order_id, product_id, quantity_ordered, unit_price, total_price) VALUES (v_po, v_prod, 100, 500, 50000); END IF; END IF;
END $$;