// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzitfcigdjbpymvebipp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aXRmY2lnZGpicHltdmViaXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTMzODAsImV4cCI6MjA2NjU4OTM4MH0.JvlZ7f0jamxZxv5ti9UOamF0iL_ZwlMpbquFhzWARZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export function to call smart-reorder edge function
export async function invokeSmartReorder(action: string, params: any) {
  return await supabase.functions.invoke('smart-reorder', {
    body: { action, ...params }
  });
}

// Export function to backfill Shopify fulfillments (processes in batches of 10)
export async function invokeBackfillShopifyFulfillments() {
  let totalUpdated = 0;
  let totalSkipped = 0;
  let totalErrors = 0;
  let offset = 0;
  let hasMore = true;

  while (hasMore) {
    const { data, error } = await supabase.functions.invoke('backfill-shopify-fulfillments', {
      body: { offset, limit: 10 }
    });

    if (error) {
      return { data: null, error };
    }

    if (data) {
      totalUpdated += data.updated || 0;
      totalSkipped += data.skipped || 0;
      totalErrors += data.errors || 0;
      hasMore = data.hasMore || false;
      offset = data.nextOffset || 0;

      // If no more batches, break
      if (!hasMore) break;
    } else {
      break;
    }
  }

  return {
    data: {
      updated: totalUpdated,
      skipped: totalSkipped,
      errors: totalErrors
    },
    error: null
  };
}